# Generated by Django 3.2 on 2023-09-08 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_auto_20230908_1305'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sumingredients',
            old_name='ingredient_id',
            new_name='ingredient',
        ),
        migrations.RenameField(
            model_name='sumingredients',
            old_name='recipe_id',
            new_name='recipe',
        ),
    ]
