# Generated by Django 3.2 on 2023-09-08 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_auto_20230908_1321'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='sumingredients',
            name='recipe_id_ingredient_id',
        ),
        migrations.AddConstraint(
            model_name='sumingredients',
            constraint=models.UniqueConstraint(fields=('recipe', 'ingredient'), name='recipe_ingredient'),
        ),
    ]
