# Generated by Django 3.2 on 2023-09-08 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_auto_20230908_1325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='ingredients',
            field=models.ManyToManyField(related_name='recipe', through='recipes.SumIngredients', to='recipes.Ingredient', verbose_name='Ингредиенты'),
        ),
    ]
